---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventilar-web
  labels:
    app: ventilar-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ventilar-web
  template:
    metadata:
      labels:
        app: ventilar-web
    spec:
      containers:
        - name: ventilar-web
          image: gabtec/test-k8s
          ports:
            - containerPort: 80
